version: '3'

services:
  apache:
    image: 'php:7.4-apache'
    env_file: ./.env
    container_name: 2022-pis-grupo1
    restart: always
    ports:
      - '80:80'
    volumes:
      - ./api:/var/www/html
    depends_on:
      - db
    links:
      - db

  db:
    image: mysql:5.7
    env_file: ./.env
    restart: always
    environment:
      MYSQL_DATABASE: $MYSQL_DB_DATABASE
      MYSQL_USER: $MYSQL_DB_USER
      MYSQL_ALLOW_EMPTY_PASSWORD : 1
      MYSQL_ROOT_PASSWORD: $MYSQL_DB_PASSWORD
    volumes:
      - ./db:/var/lib/mysql